[project]
name = "pz-api-docs"
description = "PZ API Documentation provides a comprehensive reference for the Project Zomboid API generated automatically from various datasets and sources."
requires-python = ">=3.12.3"
version = "1.0.0"
license-files = ["LICENSE"]
authors = [
  { name = "SimKDT" },
]
dependencies = [
    # sphinx dependencies
    "sphinx>=5.0",
    "furo",
    "sphinx-reredirects",

    # doc generators
    "m2r",
    "pyyaml",

    # datasets
    "pz_scripts_data @ git+https://github.com/PZ-Wiki-Modding/pz-scripts-data.git",
]